// =============================================
// products.js — Static Data for Lumière Website
// =============================================

// 🧴 PRODUCT DATA
const PRODUCTS = [
    {
        id: 1,
        name: "Gentle Foam Cleanser",
        category: "cleanser",
        price: 598,
        tag: "Bestseller",
        emoji: "🧴",
        color: "#f9e8e0",
        rating: 4.8,
        reviews: 324,
        description: "A pH-balanced foaming cleanser that removes impurities without stripping natural moisture. Enriched with aloe vera and green tea extract.",
        details: ["Suitable for all skin types", "Fragrance-free formula", "Dermatologist tested", "200ml / 6.76 fl.oz"],
        ingredients: "Aloe Vera, Green Tea Extract, Hyaluronic Acid, Niacinamide"
    },
    {
        id: 2,
        name: "Radiance Vitamin C Serum",
        category: "serum",
        price: 1298,
        tag: "Top Rated",
        emoji: "✨",
        color: "#fff3cd",
        rating: 4.9,
        reviews: 512,
        description: "A potent 15% Vitamin C serum that brightens dark spots and evens skin tone. Formulated with ferulic acid for enhanced stability and efficacy.",
        details: ["15% L-Ascorbic Acid", "Targets hyperpigmentation", "Antioxidant protection", "30ml / 1 fl.oz"],
        ingredients: "L-Ascorbic Acid, Ferulic Acid, Vitamin E, Hyaluronic Acid"
    },
    {
        id: 3,
        name: "Hydra-Guard SPF 50+",
        category: "sunscreen",
        price: 898,
        tag: "Must-Have",
        emoji: "☀️",
        color: "#e8f4f8",
        rating: 4.7,
        reviews: 289,
        description: "A lightweight, non-greasy sunscreen that offers broad-spectrum protection while providing all-day hydration. No white cast formula.",
        details: ["SPF 50+ PA++++", "No white cast", "Water-resistant 80 mins", "50ml / 1.7 fl.oz"],
        ingredients: "Zinc Oxide, Titanium Dioxide, Niacinamide, Ceramides"
    },
    {
        id: 4,
        name: "Peptide Renewal Moisturizer",
        category: "moisturizer",
        price: 1198,
        tag: "New",
        emoji: "💧",
        color: "#e8f0e8",
        rating: 4.6,
        reviews: 178,
        description: "A rich yet lightweight moisturizer infused with 5 types of peptides that stimulate collagen production and reduce fine lines.",
        details: ["5-Peptide Complex", "Anti-aging formula", "24-hour hydration", "50ml / 1.7 fl.oz"],
        ingredients: "Matrixyl 3000, Argireline, Ceramides, Squalane, Shea Butter"
    },
    {
        id: 5,
        name: "Rose Glow Essence Toner",
        category: "serum",
        price: 748,
        tag: "Fan Favorite",
        emoji: "🌹",
        color: "#f9e0ec",
        rating: 4.5,
        reviews: 203,
        description: "A hydrating essence-toner hybrid with real rose water and 10% niacinamide that minimizes pores and controls sebum production.",
        details: ["10% Niacinamide", "Real Rose Water", "Pore minimizing", "150ml / 5.07 fl.oz"],
        ingredients: "Rose Water, Niacinamide, Galactomyces, Centella Asiatica"
    },
    {
        id: 6,
        name: "Cica Repair Cream",
        category: "moisturizer",
        price: 998,
        tag: "Soothing",
        emoji: "🌿",
        color: "#e6f0e6",
        rating: 4.7,
        reviews: 156,
        description: "A calming repair cream with Centella Asiatica that soothes irritation, reduces redness, and restores the skin barrier overnight.",
        details: ["70% Centella Extract", "Barrier restoration", "Suitable for sensitive skin", "60ml / 2 fl.oz"],
        ingredients: "Centella Asiatica, Madecassoside, Allantoin, Ceramide NP"
    },
    {
        id: 7,
        name: "Charcoal Deep Cleanse Mask",
        category: "mask",
        price: 548,
        tag: "Detox",
        emoji: "🖤",
        color: "#e8e8e8",
        rating: 4.3,
        reviews: 98,
        description: "A purifying clay-charcoal mask that draws out deep-seated impurities, unclogs pores, and leaves skin refreshed and clarified.",
        details: ["Activated Charcoal", "Kaolin & Bentonite Clay", "Use 2x per week", "75ml / 2.5 fl.oz"],
        ingredients: "Activated Charcoal, Kaolin Clay, Salicylic Acid, Tea Tree Oil"
    },
    {
        id: 8,
        name: "Retinol Overnight Serum",
        category: "serum",
        price: 1498,
        tag: "Advanced",
        emoji: "🌙",
        color: "#ede0f5",
        rating: 4.8,
        reviews: 241,
        description: "A gentle 0.3% encapsulated retinol serum that renews skin cells overnight with minimal irritation. Wake up to smoother, firmer skin.",
        details: ["0.3% Encapsulated Retinol", "Reduces fine lines", "Night use only", "30ml / 1 fl.oz"],
        ingredients: "Encapsulated Retinol, Bakuchiol, Peptides, Ceramides"
    },
    {
        id: 9,
        name: "Milk Brightening Cleanser",
        category: "cleanser",
        price: 498,
        tag: "Gentle",
        emoji: "🥛",
        color: "#faf0e6",
        rating: 4.4,
        reviews: 134,
        description: "A creamy milk-based cleanser that dissolves makeup and gently brightens dull skin. Perfect for dry and sensitive skin types.",
        details: ["Milk Protein Complex", "Makeup removing", "Non-stripping formula", "180ml / 6 fl.oz"],
        ingredients: "Milk Protein, Niacinamide, Panthenol, Glycerin"
    },
    {
        id: 10,
        name: "Aqua Hydra-Boost Gel",
        category: "moisturizer",
        price: 848,
        tag: "Oil-Free",
        emoji: "💦",
        color: "#dceefb",
        rating: 4.6,
        reviews: 167,
        description: "An ultra-light water-gel moisturizer with 5x Hyaluronic Acid complex that delivers deep hydration without clogging pores.",
        details: ["5x Hyaluronic Acid", "Oil-free, non-comedogenic", "Suitable for oily skin", "50ml / 1.7 fl.oz"],
        ingredients: "Hyaluronic Acid (5 molecular weights), Polyglutamic Acid, Aloe Vera"
    },
    {
        id: 11,
        name: "Golden Glow Tinted SPF",
        category: "sunscreen",
        price: 1098,
        tag: "2-in-1",
        emoji: "🌟",
        color: "#fdf3e0",
        rating: 4.5,
        reviews: 89,
        description: "A tinted sunscreen that evens skin tone while protecting from UV damage. Available in 3 shades for a natural, dewy finish.",
        details: ["SPF 40 PA+++", "Light coverage tint", "Dewy finish", "30ml / 1 fl.oz"],
        ingredients: "Zinc Oxide, Iron Oxides, Niacinamide, Vitamin C"
    },
    {
        id: 12,
        name: "Honey & Oat Glow Mask",
        category: "mask",
        price: 448,
        tag: "Nourishing",
        emoji: "🍯",
        color: "#fff0d0",
        rating: 4.2,
        reviews: 76,
        description: "A nourishing honey and colloidal oat mask that restores radiance and deeply conditions dry, dull skin in just 15 minutes.",
        details: ["Raw Honey Extract", "Colloidal Oatmeal", "15-minute treatment", "80ml / 2.7 fl.oz"],
        ingredients: "Honey Extract, Colloidal Oatmeal, Propolis, Argan Oil"
    }
];

// 🏆 MEMBERS DATA
const MEMBERS = [
    {
        id: 1,
        name: "Sofia Reyes",
        type: "seller",
        rank: 1,
        sales: "₱248,500",
        avatar: "SR",
        location: "Manila",
        badge: "Diamond Lumière",
        color: "#f9e8e0",
        accentColor: "#d4a574",
        tagline: "Sharing glow one serum at a time 🌟",
        joinedYear: 2022
    },
    {
        id: 2,
        name: "Grace Villanueva",
        type: "recruiter",
        rank: 2,
        sales: "₱186,200",
        avatar: "GV",
        location: "Cebu",
        badge: "Platinum Lumière",
        color: "#fdf3e0",
        accentColor: "#b5956b",
        tagline: "Building a community of glowing women ✨",
        joinedYear: 2022
    },
    {
        id: 3,
        name: "Ana Lim",
        type: "seller",
        rank: 3,
        sales: "₱162,400",
        avatar: "AL",
        location: "Davao",
        badge: "Platinum Lumière",
        color: "#e8f0e8",
        accentColor: "#7a9b76",
        tagline: "Glow is a lifestyle, not a trend 🌿",
        joinedYear: 2023
    },
    {
        id: 4,
        name: "Bianca Santos",
        type: "recruiter",
        rank: 4,
        sales: "₱134,800",
        avatar: "BS",
        location: "Quezon City",
        badge: "Gold Lumière",
        color: "#f9e0ec",
        accentColor: "#c4708a",
        tagline: "Pink skies and glowing skin 🌸",
        joinedYear: 2023
    },
    {
        id: 5,
        name: "Jessa Morales",
        type: "rising",
        rank: 5,
        sales: "₱98,600",
        avatar: "JM",
        location: "Iloilo",
        badge: "Silver Lumière",
        color: "#e8e8f5",
        accentColor: "#7a7ab5",
        tagline: "Rising star with big glow energy ⭐",
        joinedYear: 2024
    },
    {
        id: 6,
        name: "Trisha Delos Reyes",
        type: "rising",
        rank: 6,
        sales: "₱87,200",
        avatar: "TD",
        location: "Batangas",
        badge: "Silver Lumière",
        color: "#e8f4f8",
        accentColor: "#5b96b0",
        tagline: "Every drop of serum counts 💧",
        joinedYear: 2024
    },
    {
        id: 7,
        name: "Lovely Cruz",
        type: "seller",
        rank: 7,
        sales: "₱76,400",
        avatar: "LC",
        location: "Pampanga",
        badge: "Bronze Lumière",
        color: "#fff3cd",
        accentColor: "#b08a30",
        tagline: "Skincare junkie and proud 🧴",
        joinedYear: 2024
    },
    {
        id: 8,
        name: "Mariz Gonzales",
        type: "recruiter",
        rank: 8,
        sales: "₱68,900",
        avatar: "MG",
        location: "Laguna",
        badge: "Bronze Lumière",
        color: "#ede0f5",
        accentColor: "#9b5ebd",
        tagline: "Empowering women to glow and earn 💜",
        joinedYear: 2024
    }
];

// 🏅 AWARDS
const AWARDS = [
    { icon: "💎", name: "Diamond Achiever", desc: "₱200K+ lifetime sales", color: "#e8f0fb" },
    { icon: "🏆", name: "Top Seller 2024", desc: "Highest monthly revenue", color: "#fff3cd" },
    { icon: "⭐", name: "Rising Star", desc: "Fastest growing member", color: "#fdf3e0" },
    { icon: "🌸", name: "Community Builder", desc: "10+ active recruits", color: "#f9e0ec" },
    { icon: "🌿", name: "Natural Advocate", desc: "Eco-conscious ambassador", color: "#e8f0e8" },
    { icon: "✨", name: "Glow Goddess", desc: "Customer favorite 3 months", color: "#f9e8e0" }
];